apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: soccerfootballstuff
portForward:
  - resourceType: service
    resourceName: soccerfootballstuff-rabbitmq-svc
    port: 15672
manifests:
  rawYaml:
    - ./infra/k8s/*
