apiVersion: apps/v1
kind: Deployment
metadata:
  name: soccerfootballstuff-rabbitmq-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soccerfootballstuff-rabbitmq
  template:
    metadata:
      labels:
        app: soccerfootballstuff-rabbitmq
    spec:
      containers:
        - name: soccerfootballstuff-rabbitmq
          image: jzenon13/soccerfootballstuff-rabbitmq:management
          resources:
            requests:
              memory: "300Mi"
              cpu: "500m"
            limits:
              memory: "600Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: soccerfootballstuff-rabbitmq-svc
spec:
  selector:
    app: soccerfootballstuff-rabbitmq
  ports:
    - name: events
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: admin-portal
      protocol: TCP
      port: 15672
      targetPort: 15672
